# Generated by Django 4.2.3 on 2023-08-01 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0003_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('amount_recieved', models.IntegerField(default=0)),
                ('issued_to', models.CharField(max_length=50)),
                ('unit_price', models.IntegerField(default=0)),
                ('branch_name', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spareapp.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
