# Generated by Django 4.2.3 on 2023-08-01 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0004_sale_delete_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_of_arrival',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
