# Generated by Django 4.2.3 on 2023-08-01 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0005_category_date_of_arrival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_of_arrival',
        ),
        migrations.AddField(
            model_name='product',
            name='date_of_arrival',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
